[project]
name = "ifac26-paper-elobaid"
version = "0.1.0"
description = "Rigid Formation Control on Parametric Curves"
authors = ["Mohamed Elobaid <mohamed.elobaid@kaust.edu.sa>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.9"
numpy = "*"
matplotlib = "*"
scipy = "*"

cxx-compiler = "*"
cmake = "*"
make = "*"

mujoco = "*"
glfw = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
libglvnd-glx-cos7-x86_64 = "*"
xorg-libx11 = "*"
xorg-libxext = "*"



[tasks]
## cpp
cpp-build = "cmake -S code/cpp -B code/cpp/build && cmake --build code/cpp/build"
crazyflie-example = { cmd = "code/cpp/build/crazyflie_sim", depends-on = ["cpp-build"] }

## python
finder-example = "python code/python/formation-finder-example.py"
simulation-example = "python code/python/multi_agent_simulation.py"


